version: "3.8"

services:
  main_db:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INIT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INIT_PASSWORD}"
    ports:
      - "27011:27017"
    networks:
      - pt-mongo-dev-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo main_db:27017/test --quiet
      timeout: 30s
      interval: 5s
      retries: 6
    container_name: pt-main-mongodb
  consume:
    image: pt-consume
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INIT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INIT_PASSWORD}"
    networks:
      - pt-mongo-dev-network
    depends_on:
      main_db:
        condition: service_healthy
    container_name: pt-main-mongodb-consume

networks:
  pt-mongo-dev-network:
    name: pt-dev-network
    external: true
